apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kubeupdater.fullname" . }}
  labels:
    {{- include "kubeupdater.labels" . | nindent 4 }}
data:
  kubeupdater: |
{{ .Files.Get "bin/kubeupdater" | indent 4 }}
