apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeupdater
  namespace: kube-system
  labels:
    app: {{ template "kubeupdater.name" . }}
    chart: {{ template "kubeupdater.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  everything.repo: |
    [everything]
    name=everything
    enabled=1
    baseurl={{ .Values.base }}{{ .Values.version }}
    gpgkey = file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
             {{ .Values.base }}{{ .Values.version }}/repodata/RPM-GPG-KEY
    gpgcheck = 1
    repo_gpgcheck = 1
    keepcache = 0
