apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubeupdater-node
  namespace: kube-system
  labels:
    app: {{ template "kubeupdater.name" . }}
    chart: {{ template "kubeupdater.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  resourceNames:
  - kubeupdater
  verbs:
  - get
  - watch
