{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "kubeupdater.fullname" . }}
  labels:
    app: {{ template "kubeupdater.name" . }}
    chart: {{ template "kubeupdater.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: unrestricted-psp
subjects:
- kind: ServiceAccount
  name: {{ template "kubeupdater.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
