{{- if and .Values.rbac.create .Values.podSecurityPolicy.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "kubeupdater.fullname" . }}
  labels:
    {{- include "kubeupdater.labels" . | nindent 4 }}
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - {{ template "kubeupdater.fullname" . }}
{{- end }}
