# Copied from helm stable repo. Maintainer switched.
apiVersion: v1
appVersion: 2.8.1
description: Elegantly enables a Tiller per namespace in RBAC-enabled clusters
home: https://github.com/kubernetes/charts/tree/master/stable/magic-namespace
maintainers:
- email: kevin.fox@pnnl.gov
  name: kfox1111
#- email: kent.rancourt@microsoft.com
#  name: krancour
name: magic-namespace
version: 0.5.2
