dependencies:
- name: magic-namespace
  alias: adminmagicnamespace
  version: "0.5.2"
  repository: "https://charts.helm.sh/stable"
  condition: adminmagicnamespace.enabled
- name: magic-namespace
  alias: magicnamespace
  version: "0.5.2"
  repository: "https://charts.helm.sh/stable"
- name: nginx-ingress
  alias: ingress
  version: "1.34.2"
  repository: "https://charts.helm.sh/stable"
  condition: ingress.nginx.enabled
