kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "gitlab-runner-operator.fullname" . }}-fl
  labels:
{{ include "gitlab-runner-operator.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "gitlab-runner-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "gitlab-runner-operator.fullname" . }}-fl
  apiGroup: rbac.authorization.k8s.io
