---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "tenant-namespace-operator.fullname" . }}-fl
  labels:
{{ include "tenant-namespace-operator.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "tenant-namespace-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "tenant-namespace-operator.fullname" . }}-fl
  apiGroup: rbac.authorization.k8s.io

---
#This is needed so that it can give out admin access to things it creates
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "tenant-namespace-operator.fullname" . }}-adm
  labels:
{{ include "tenant-namespace-operator.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "tenant-namespace-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
