{{- $global := . }}
{{- $base := dict "resources" .Values.resources "nodeSelector" .Values.nodeSelector "affinity" .Values.affinity "tolerations" .Values.tolerations "config" .Values.config }}
{{- $items := prepend .Values.extraInstances $base }}
{{- range $idx, $item := $items }}
{{- $config := mergeOverwrite $item.config $global.Values.common.config }}
{{- $res := set $item "config" $config }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "pnnlmiscscripts.smartctl-exporter.fullname" $global }}-{{ $idx }}
  labels:
    app: {{ template "pnnlmiscscripts.smartctl-exporter.name" $global }}
    chart: {{ template "pnnlmiscscripts.smartctl-exporter.chart" $global }}
    release: {{ $global.Release.Name }}
    heritage: {{ $global.Release.Service }}
    idx: i{{ $idx }}
spec:
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ template "pnnlmiscscripts.smartctl-exporter.name" $global }}
      release: {{ $global.Release.Name }}
      idx: i{{ $idx }}
  template:
    metadata:
      labels:
        app: {{ template "pnnlmiscscripts.smartctl-exporter.name" $global }}
        release: {{ $global.Release.Name }}
        idx: i{{ $idx }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum | quote }}
    spec:
      containers:
      - image: {{ dict "dot" . "section" $global.Values.image | include "pnnlmiscscripts.smartctl-exporter.image" }}
        imagePullPolicy: {{ $global.Values.image.pullPolicy }}
        name: main
        securityContext:
          privileged: true
        ports:
        - name: http
          containerPort: 9633
          protocol: TCP
        resources:
{{ toYaml $item.resources | indent 10 }}
        volumeMounts:
        - mountPath: /hostdev
          name: dev
        - mountPath: /etc/smartctl_exporter.yaml
          subPath: smartctl_exporter.yaml
          name: config
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      serviceAccountName: {{ template "pnnlmiscscripts.smartctl-exporter.fullname" $global }}
      volumes:
      - configMap:
          name: {{ template "pnnlmiscscripts.smartctl-exporter.fullname" $global }}-{{ $idx }}
        name: config
      - hostPath:
          path: /dev
        name: dev
    {{- with $item.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with $item.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with $item.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end }}
