{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "pnnlmiscscripts.smartctl-exporter.fullname" . }}
  labels:
    app: {{ template "pnnlmiscscripts.smartctl-exporter.name" . }}
    chart: {{ template "pnnlmiscscripts.smartctl-exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.rbac.podSecurityPolicy }}
subjects:
- kind: ServiceAccount
  name: {{ template "pnnlmiscscripts.smartctl-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
