{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "pnnlmiscscripts.smartctl-exporter.fullname" . }}
  labels:
    app: {{ template "pnnlmiscscripts.smartctl-exporter.name" . }}
    chart: {{ template "pnnlmiscscripts.smartctl-exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if ne (len .Values.serviceMonitor.extraLabels) 0 }}
{{ toYaml .Values.serviceMonitor.extraLabels | indent 4 }}
{{- end }}
{{- if hasKey .Values.serviceMonitor "namespace" }}
  namespace: {{ .Values.serviceMonitor.namespace }}
{{- end }}
spec:
  endpoints:
  - interval: 60s
    path: /metrics
    port: http
    scheme: http
    scrapeTimeout: 30s
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ template "pnnlmiscscripts.smartctl-exporter.name" . }}
      release: {{ .Release.Name }}
{{- end }}
