apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pnnlmiscscripts.ipmi-exporter-full.fullname" . }}
  labels:
    {{- include "pnnlmiscscripts.ipmi-exporter-full.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pnnlmiscscripts.ipmi-exporter-full.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum | quote }}
      labels:
        {{- include "pnnlmiscscripts.ipmi-exporter-full.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "pnnlmiscscripts.ipmi-exporter-full.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ dict "dot" . "section" .Values.ipmiExporter | include "pnnlmiscscripts.ipmi-exporter.image" }}
          imagePullPolicy: {{ .Values.ipmiExporter.imagePullPolicy }}
          command:
          - /usr/bin/ipmi_exporter
          - --config.file
          - /etc/ipmi-exporter/ipmi.yaml
          ports:
            - name: http
              containerPort: 9290
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: config
            mountPath: /etc/ipmi-exporter
      volumes:
      - name: config
        secret:
          secretName: {{ template "pnnlmiscscripts.ipmi-exporter-full.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
