apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pnnlmiscscripts.ipmi-exporter-full.fullname" . }}
  labels:
    {{- include "pnnlmiscscripts.ipmi-exporter-full.labels" . | nindent 4 }}
data:
  ipmi.yaml: {{ toYaml .Values.config | b64enc }}
