{{- if .Values.limitRange.enabled }}
apiVersion: v1
kind: LimitRange
metadata:
    name: {{ .Release.Name }}
    namespace: {{ .Values.magicnamespace.namespace }}
    labels:
        app: {{ template "namespace.name" . }}
        chart: {{ template "namespace.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
spec:
  limits:
{{ toYaml .Values.limitRange.limits | indent 4 }}
{{- end }}
